# Generated by Django 4.1.7 on 2023-03-25 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='in_progress', max_length=255),
        ),
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_reason', to='task.task')),
            ],
        ),
    ]
