# Generated by Django 4.1.7 on 2023-03-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_process_rejectionreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RejectionReason',
        ),
    ]
