# Generated by Django 4.1.7 on 2023-03-25 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_reason_delete_rejectionreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoreTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
            options={
                'verbose_name': 'Restored Task',
                'verbose_name_plural': 'Restored Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
