# Generated by Django 4.1.7 on 2023-03-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_restoretask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
