# Generated by Django 4.1.7 on 2023-03-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.CharField(choices=[('в процесі', 'In Progress'), ('прийнято', 'Accepted'), ('відхилено', 'Rejected')], default='in_progress', max_length=255),
        ),
    ]
