# Generated by Django 4.1.7 on 2023-03-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_task_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('process of recovery', 'Process of Recovery')], default='in_progress', max_length=255),
        ),
    ]
